FROM java:8
# Copying jdk from OS directory which DockerFile file directory to image directory  
# COPY jdk1.8.0_144 /usr/local/jdk1.8.0_144
# Configure jdk enviroment
# ENV JAVA_HOME /usr/local/jdk1.8.0_144
# ENV PATH $PATH:$JAVA_HOME/bin:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/jre/lib/rt.jar
# Copy application package include start application shell script
COPY dockerApp /usr/local/dockerApp

COPY startService-linux.sh /usr/local/

RUN chmod 770 /usr/local/startService-linux.sh

RUN pwd

WORKDIR /usr/local

ENTRYPOINT ["./startService-linux.sh"]
#ENTRYPOINT ["java","-cp","./dockerApp/config:./dockerApp/lib/*:./dockerApp/*","com.sunshine.boot.VehicleDeckBootApplication"]
