kind: Deployment
apiVersion: apps/v1beta1
metadata:
  labels:
    k8s-app: springboot-app
  name: springboot-app
  namespace: default
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: mics-app
    spec:
      containers:
      - name: mics-app
        image: yangdockerrepos/testrepos:dkapptest_1.0
        ports:
        - containerPort: 8888
---
#------------------------springboot service------------------------------
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: springboot-app
  name: springboot-app
  namespace: default
spec:
  type: NodePort
  selector:
    app: mics-app
  ports:
    - protocol: TCP
      port: 8889
      targetPort: 8888
      nodePort: 30000
