kind: Deployment
apiVersion: apps/v1beta1
metadata:
  labels:
    k8s-app: mics-app
  name: misc-app
  namespace: kong
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: demoapp
        image: 192.168.2.32:5000/dockerapp:v1.0
        ports:
        - containerPort: 8088
---
#------------------------springboot service------------------------------
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: mics-app
  name: mics-app
  namespace: kong
spec:
  selector:
    app: demoapp
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
